# Generated by Django 5.2.17 on 2026-10-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("password", models.CharField(max_length=255)),
                ("email_code", models.CharField(max_length=6)),
                ("phone_code", models.CharField(blank=True, default="", max_length=6)),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
