# Generated by Django 6.1.1 on 2026-09-26 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobevent",
            index=models.Index(
                fields=["user", "kind", "created_at"], name="jobs_event_user_kind_idx"
            ),
        ),
    ]
